# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev x11-common libx11-dev -y
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    - name: Install Golang dependencies
      run: go get .
    - name: Build
      run: go build -v ./...
    - name: Test with the Go CLI
      run: go test -v ./...
