# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-11-arm
    steps:
    - uses: actions/checkout@v4
    # - name: Install Windows dependencies
    #   run: |
    #     winget install --id NVIDIA.GeForceDriver -e --accept-package-agreements --accept-source-agreements
    - name: Set up C/C++ Compiler
      id: setup-compiler
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-latest
    - name: Verify GCC Installation
      run: |
        gcc --version
        g++ --version
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    - name: Install Golang dependencies
      run: go get .
    - name: Build
      run: go build -v ./...
    - name: Test with the Go CLI
      run: go test -v ./...
